import type { Metadata } from 'next'
import './globals.css'
import Header from '../components/header'
import Footer from '@/components/home/footer'
import FloatingMenu from '@/components/FloatingMenu'


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='overflow-x-hidden relative'>
        <Header />
        {children}
        {/* <FloatingMenu /> */}
        <Footer />
      </body>
    </html>
  )
}
